'use client';
import { useState } from 'react';
import { DashboardShell } from '@/components/dashboard-shell';
import { useChecklistStore } from '@/features/checklists/store';
import { areas,assets,templates, ChecklistStatus } from '@/features/checklists/mock-data';

const statusClass:Record<ChecklistStatus,string>={'Pendiente':'pending','En progreso':'progress','Finalizado':'done','Aprobado':'approved','Vencido':'overdue'};
function Status({s}:{s:ChecklistStatus}){return <span className={'status '+statusClass[s]}>{s}</span>}
function Dashboard(){const list=useChecklistStore(s=>s.checklists); const done=list.filter(x=>x.status==='Finalizado'||x.status==='Aprobado').length;return <div className="page"><h1 className="page-title">Buenos días, Lucía</h1><p className="page-subtitle">Aquí está el estado operativo del hotel hoy.</p><div className="kpis"><K label="Creados hoy" value="32" note="↑ 12% vs. ayer"/><K label="Pendientes" value={String(list.filter(x=>x.status==='Pendiente').length+8)} note="5 vencen antes de 12:00"/><K label="Finalizados" value={`${done+22}/32`} note="75% completado"/><K label="Tiempo promedio" value="18m 42s" note="↓ 2m 14s vs. semana"/><K label="Cumplimiento SLA" value="94.6%" note="↑ 1.8% este mes"/></div><div className="grid"><section className="card"><h2 className="card-title">Cumplimiento por área</h2><p className="card-sub">Checklists completados durante el día</p>{[['Habitaciones',88],['Alimentos y bebidas',96],['Recepción',92],['Piscina',74],['Mantenimiento',81]].map(([a,n])=><div className="bar-row" key={String(a)}><span>{a}</span><div className="bar"><i style={{width:`${n}%`}}/></div><b>{n}%</b></div>)}</section><section className="card"><h2 className="card-title">Actividad reciente</h2><p className="card-sub">Actualizaciones del equipo</p>{[['Lucía completó Habitación 410','Hace 4 min'],['Carlos inició Apertura de restaurante','Hace 12 min'],['Sofía reportó una incidencia en Torre Norte','Hace 28 min'],['Ana aprobó Inspección de lobby','Hace 43 min']].map(x=><div className="activity" key={x[0]}><i className="activity-dot"/><div><p>{x[0]}</p><small>{x[1]}</small></div></div>)}</section></div></div>}
function K(p:{label:string,value:string,note:string}){return <div className="card"><div className="kpi-label">{p.label}</div><div className="kpi-value">{p.value}</div><div className="kpi-change">{p.note}</div></div>}
function Instances(){const {checklists,updateStatus,addChecklist}=useChecklistStore();const [creating,setCreating]=useState(false);const [filter,setFilter]=useState('Todos');return <div className="page"><div className="toolbar"><div><h1 className="page-title">Checklists</h1><p className="page-subtitle">Gestiona las ejecuciones operativas del hotel.</p></div><button className="btn btn-primary" onClick={()=>setCreating(true)}>+ Crear checklist</button></div>{creating&&<Create onClose={()=>setCreating(false)} onSave={(x)=>{addChecklist(x);setCreating(false)}}/>}<div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)} className="btn btn-secondary"><option>Todos</option><option>Pendiente</option><option>En progreso</option><option>Finalizado</option></select><span className="muted" style={{fontSize:13}}>{checklists.length} resultados</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Checklist</th><th>Área / activo</th><th>Asignado a</th><th>Progreso</th><th>Vence</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{checklists.filter(x=>filter==='Todos'||x.status===filter).map(x=><tr key={x.id}><td><b>{x.template}</b><br/><span className="muted">{x.id}</span></td><td>{x.area}<br/><span className="muted">{x.asset}</span></td><td>{x.assigned}</td><td>{x.progress}%</td><td>{x.due}</td><td><Status s={x.status}/></td><td className="actions">{x.status==='Pendiente'&&<button onClick={()=>updateStatus(x.id,'En progreso')}>Iniciar</button>}{x.status==='En progreso'&&<button onClick={()=>updateStatus(x.id,'Finalizado')}>Finalizar</button>}{x.status==='Finalizado'&&<button onClick={()=>updateStatus(x.id,'Aprobado')}>Aprobar</button>}{(x.status==='Aprobado'||x.status==='Vencido')&&<button onClick={()=>updateStatus(x.id,'En progreso')}>Reabrir</button>}</td></tr>)}</tbody></table></div></div>}
function Create({onClose,onSave}:{onClose:()=>void;onSave:(x:any)=>void}){const [template,setTemplate]=useState(templates[0][0]);const [asset,setAsset]=useState(assets[0][0]);return <div className="panel" style={{marginBottom:20}}><h2 className="card-title">Crear checklist manual</h2><p className="card-sub">Genera una instancia desde un template para un activo.</p><div className="form-grid"><div className="field"><label>Template</label><select value={template} onChange={e=>setTemplate(e.target.value)}>{templates.map(x=><option key={x[0]}>{x[0]}</option>)}</select></div><div className="field"><label>Activo</label><select value={asset} onChange={e=>setAsset(e.target.value)}>{assets.map(x=><option key={x[0]}>{x[0]}</option>)}</select></div><div className="field"><label>Asignar a</label><input defaultValue="Lucía Moreno"/></div><div className="field"><label>Hora límite</label><input type="time" defaultValue="14:00"/></div></div><div className="form-actions"><button className="btn btn-secondary" onClick={onClose}>Cancelar</button><button className="btn btn-primary" onClick={()=>onSave({template,asset,area:templates.find(x=>x[0]===template)?.[1]??'Habitaciones',assigned:'Lucía Moreno',status:'Pendiente',due:'14:00'})}>Crear checklist</button></div></div>}
function Catalog({type}:{type:string}){let content:string[][]=type==='Áreas'?areas:type==='Activos'?assets:type==='Templates'?templates:[];return <div className="page"><div className="toolbar"><div><h1 className="page-title">{type}</h1><p className="page-subtitle">Configuración operacional del hotel.</p></div><button className="btn btn-primary">+ Crear {type.slice(0,-1)}</button></div><div className="table-wrap"><table className="table"><thead><tr>{(type==='Áreas'?['Nombre','Activos','Descripción','Estado']:type==='Activos'?['Nombre','Tipo','Área','Estado']:['Nombre','Área','Recurrencia','Tareas','Duración']).map(x=><th key={x}>{x}</th>)}<th></th></tr></thead><tbody>{content.map(x=><tr key={x[0]}>{x.map(y=><td key={y}>{y==='Activo'?<Status s="Aprobado"/>:y}</td>)}<td className="actions"><button>Editar</button><button>Ver</button></td></tr>)}</tbody></table></div></div>}
function Placeholder({title}:{title:string}){return <div className="page"><h1 className="page-title">{title}</h1><p className="page-subtitle">Módulo preparado para conectarse con la API.</p><div className="card empty">La vista de {title.toLowerCase()} estará disponible con datos en tiempo real durante la integración.</div></div>}
export default function App(){const [page,setPage]=useState('dashboard');let child=page==='dashboard'?<Dashboard/>:page==='instances'?<Instances/>:page==='areas'?<Catalog type="Áreas"/>:page==='assets'?<Catalog type="Activos"/>:page==='templates'?<Catalog type="Templates"/>:<Placeholder title={page==='reports'?'Reportes':page==='users'?'Usuarios':'Configuración'}/>;return <DashboardShell page={page} onPage={setPage}>{child}</DashboardShell>}
